# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

BITLY_USERNAME: 'username'
BITLY_API_KEY: 'key'


production:
  SMTP_ADDRESS: 'xxx'
  SMTP_PORT: 555
  SMTP_USERNAME: 'xxx@gmail.com'
  SMTP_PASSWORD: 'pass'
  SMTP_AUTHENTICATION: 'plain'
  SMTP_ENABLE_STARTTLS_AUTO: true

  EXCEPTION_NOTIFIER_EMAIL_PREFIX: '[fhu_error]'
  EXCEPTION_NOTIFIER_SENDER_ADDRESS: 'notifier <from@smthing.com>'
  EXCEPTION_NOTIFIER_RECIPIENTS: 'to@smthing.com'

